name = "GCom"
uuid = "c442aa85-5626-4e74-944d-fad50fba57b5"
authors = ["Matt Karikomi <mattkarikomi@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
